### ISSUE TITLE
Add a Contribution Guide to the Repository

### ISSUE THREAD

**Issue by samuelpsouza** [samuelpsouza/poa#3]
**Task: Add a Contribution Guide to the Repository**

**Description:** Create a contribution guide to help users understand how to contribute to the open-source project.

**Objective:**

* Provide clear guidelines for contributors on how to contribute to the project
* Encourage community involvement and reduce the burden on maintainers

**Tasks:**

1. Create a new file named "CONTRIBUTING.md" (or similar) in the project's root directory
2. Write a clear and concise introduction to the project and its contribution process
3. Outline the different types of contributions the project accepts (e.g. code, documentation, testing, etc.)
4. Provide detailed instructions for:
	* Forking the project
	* Cloning and setting up the development environment
	* Creating a new branch for changes
	* Submitting a pull request
5. Include information on coding style, testing, and debugging
6. Add a section for common issues or known problems that contributors may encounter
7. Include a section for contributors to report any issues or bugs they encounter while contributing

**Deliverables:**

* A new "CONTRIBUTING.md" file in the project's root directory
* A comprehensive guide that outlines the contribution process and provides helpful tips and resources

**Comment by igocoelho** [comment]
I´ll do this task @samuelpsouza.
